/**
 * StudentManagerAPI2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Buyer } from './buyer';
import { Material } from './material';


export interface Building { 
    id?: number;
    name?: string | null;
    address?: string | null;
    description?: string | null;
    year?: string | null;
    material?: Material;
    buyers?: Array<Buyer> | null;
}

